from django.urls import path

from .views import (
    complete_study_session,
    document_chat,
    document_chat_ask,
    document_ai_prepare_status,
    document_detail,
    exam_simulator,
    document_flashcards,
    document_file,
    document_quiz,
    documents_list,
    community_chat,
    multi_document_chat,
    library_home,
    library_moderation,
    library_submissions,
    library_upload,
    moderate_library_document,
    start_study_session,
    study_session_detail,
    study_document,
    flashcard_history,
    multi_document_study,
    quiz_history,
    upload_document,
)

urlpatterns = [
    path('', documents_list, name='documents_list'),
    path('upload/', upload_document, name='upload_document'),
    path('library/', library_home, name='library_home'),
    path('library/upload/', library_upload, name='library_upload'),
    path('library/submissions/', library_submissions, name='library_submissions'),
    path('library/community/', community_chat, name='community_chat'),
    path('library/moderation/', library_moderation, name='library_moderation'),
    path('library/moderation/<int:document_id>/<str:action>/', moderate_library_document, name='moderate_library_document'),
    path('multi-study/', multi_document_study, name='multi_document_study'),
    path('multi-document-chat/', multi_document_chat, name='multi_document_chat'),
    path('quiz-history/', quiz_history, name='quiz_history'),
    path('flashcard-history/', flashcard_history, name='flashcard_history'),
    path('study-session/start/<int:document_id>/', start_study_session, name='start_study_session'),
    path('study-session/<int:session_id>/', study_session_detail, name='study_session_detail'),
    path('study-session/complete/<int:session_id>/', complete_study_session, name='complete_study_session'),
    path('chat/<int:document_id>/', document_chat, name='document_chat'),
    path('chat/<int:document_id>/ask/', document_chat_ask, name='document_chat_ask'),
    path('prepare/<int:document_id>/<str:kind>/status/', document_ai_prepare_status, name='document_ai_prepare_status'),
    path('study/<int:document_id>/', study_document, name='study_document'),
    path('exam/<int:document_id>/', exam_simulator, name='exam_simulator'),
    path('quiz/<int:document_id>/', document_quiz, name='document_quiz'),
    path('flashcards/<int:document_id>/', document_flashcards, name='document_flashcards'),
    path('<int:document_id>/', document_detail, name='document_detail'),
    path('<int:document_id>/file/', document_file, name='document_file'),
]
