# Generated by Django 6.0.6 on 2026-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
