# Generated by Django 6.0.6 on 2026-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
