# Generated by Django 6.0.6 on 2026-06-18 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_flashcards_status_document_processing_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('first_upload', 'First Upload'), ('first_quiz', 'First Quiz'), ('quiz_master', 'Quiz Master'), ('study_streak', 'Study Streak'), ('knowledge_100', 'Knowledge 100'), ('knowledge_500', 'Knowledge 500'), ('knowledge_1000', 'Knowledge 1000')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge_type'), name='unique_user_achievement_badge')],
            },
        ),
    ]
