# Generated by Django 6.0.6 on 2026-06-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('medicine', 'Medicine'), ('engineering', 'Engineering'), ('economics', 'Economics'), ('computer_science', 'Computer Science'), ('law', 'Law'), ('business', 'Business'), ('science', 'Science'), ('other', 'Other')], max_length=40)),
                ('kind', models.CharField(choices=[('request', 'Request lectures'), ('offer', 'Offer material'), ('discussion', 'Discussion')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field', models.CharField(choices=[('medicine', 'Medicine'), ('engineering', 'Engineering'), ('economics', 'Economics'), ('computer_science', 'Computer Science'), ('law', 'Law'), ('business', 'Business'), ('science', 'Science'), ('other', 'Other')], max_length=40)),
                ('document_type', models.CharField(choices=[('lecture', 'Lecture'), ('exam', 'Old Exam'), ('notes', 'Notes'), ('book', 'Book / Chapter'), ('other', 'Other')], max_length=30)),
                ('course_name', models.CharField(max_length=160)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='library/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('safety_scan_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_library_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
