# Generated by Django 6.0.6 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_communitymessage_librarydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardattempt',
            name='average_score',
            field=models.FloatField(),
        ),
    ]
